### ISSUE TITLE
Unicode 文本分段时可能存在问题

### ISSUE THREAD

**Issue by Yesterday17** [abusetelegram/kongebot#2]
输入：
👨‍👩‍👧‍👦

期望输出：
👨‍👩‍👧‍👦

实际输出：
👨 ‍ 👩 ‍ 👧 ‍ 👦

原因：
👨‍👩‍👧‍👦 =👨 U+200D + 👩 U+200D + 👧 + U+200D + 👦

可能的解决方案：
https://github.com/tc39/proposal-intl-segmenter

（（

**Comment by NeverBehave** [comment]
唉，这个就等标准化实现吧
过于真实

**Comment by NeverBehave** [comment]
https://github.com/abusetelegram/kongebot/pull/1 
等一下, 我发现这个解决了这个问题...

**Comment by NeverBehave** [comment]
c987d65
